# NOTE: this file is generated by scripts/generate-tmux-formula.py
# Do not edit by hand; change the script and run it again.
#
# Derived from homebrew-core with a single addition: an Info.plist is linked
# into the binary so macOS recognises tmux for Local Network Privacy. Without
# that patch, anything you run inside tmux gets EHOSTUNREACH on LAN addresses.
#
# Background: https://colosieve.com/posts/fixing-tmux-local-network-privacy-macos/

class Tmux < Formula
  desc "Terminal multiplexer (with Info.plist for macOS Local Network Privacy)"
  homepage "https://tmux.github.io/"
  url "https://github.com/tmux/tmux/releases/download/3.7c/tmux-3.7c.tar.gz"
  sha256 "7c60cae9a0e25288e2e24750aafc9e8800fc7fd4555e447e1b29ee4201cfb3bf"
  license "ISC"
  compatibility_version 1

  livecheck do
    url :stable
    regex(/v?(\d+(?:\.\d+)+[a-z]?)/i)
    strategy :github_latest
  end


  head do
    url "https://github.com/tmux/tmux.git", branch: "master"

    depends_on "autoconf" => :build
    depends_on "automake" => :build
    depends_on "libtool" => :build
  end

  depends_on "pkgconf" => :build
  depends_on "libevent"
  depends_on "ncurses"
  depends_on "utf8proc"

  uses_from_macos "bison" => :build # for yacc

  on_macos do
    # https://github.com/tmux/tmux/blob/62044f02dff22d304da78ac81b69afcf84872ac7/CHANGES#L169-L170
    # https://github.com/tmux/tmux/issues/5385
    depends_on "jemalloc"
  end

  def install

    if OS.mac?
      (buildpath/"Info.plist").write <<~XML
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleIdentifier</key>
            <string>com.github.tmux</string>
            <key>CFBundleName</key>
            <string>tmux</string>
            <key>CFBundleVersion</key>
            <string>#{version}</string>
            <key>NSLocalNetworkUsageDescription</key>
            <string>tmux runs terminal sessions that may access hosts on the local network.</string>
        </dict>
        </plist>
      XML

      ENV.append "LDFLAGS", "-Wl,-sectcreate,__TEXT,__info_plist,#{buildpath}/Info.plist"
    end
    system "sh", "autogen.sh" if build.head?

    args = %W[
      --enable-sixel
      --sysconfdir=#{etc}
      --enable-utf8proc
    ]

    # tmux finds the `tmux-256color` terminfo provided by our ncurses
    # and uses that as the default `TERM`, but this causes issues for
    # tools that link with the very old ncurses provided by macOS.
    # https://github.com/Homebrew/homebrew-core/issues/102748
    args << "--with-TERM=screen-256color" if OS.mac? && MacOS.version < :sonoma

    system "./configure", *args, *std_configure_args
    system "make", "install"

    pkgshare.install "example_tmux.conf"

    if OS.mac?
      # Sign ad-hoc after the plist has been linked in; without a valid
      # signature macOS ignores the section.
      system "codesign", "--sign", "-", "--force", bin/"tmux"

      # `tmux -V` cannot carry a marker: plugin managers parse that string and
      # compare it numerically, so a suffix would break them. This helper gives
      # the same answer in one command instead.
      (bin/"tmux-lnp-check").write <<~SH
        #!/bin/sh
        # Report whether a tmux is the patched build from this tap.
        # Checks the tmux in PATH, or the binary given as first argument.

        bin=${1:-$(command -v tmux)}
        [ -n "$bin" ] && [ -x "$bin" ] || { echo "tmux: not found"; exit 1; }

        plist=no
        otool -l "$bin" 2>/dev/null | grep -q __info_plist && plist=yes
        ident=$(codesign -dvvv "$bin" 2>&1 | sed -n 's/^Identifier=//p')

        echo "binary:     $bin"
        echo "version:    $("$bin" -V 2>/dev/null)"
        echo "Info.plist: $plist"
        echo "identifier: ${ident:-none}"

        if [ "$plist" = yes ] && [ "$ident" = com.github.tmux ]; then
          echo "result:     patched build, Local Network Privacy can work"
          exit 0
        fi

        echo "result:     UNPATCHED, no Info.plist (probably homebrew-core's tmux)"
        echo "fix:        brew install --build-from-source frankhommers/tap/tmux"
        exit 1
      SH
      chmod 0755, bin/"tmux-lnp-check"
    end
  end

  def caveats
    return unless OS.mac?

    <<~EOS
      This tmux embeds an Info.plist so macOS recognises it for Local Network
      Privacy.

      A running tmux server keeps the old binary in memory. Start a separate
      server to test without losing your sessions:

        tmux -L test new-session

      If no prompt appears, go to System Settings -> Privacy & Security ->
      Local Network and enable 'tmux'.

      To check which tmux you are running (this build or homebrew-core's
      unpatched one):

        tmux-lnp-check
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tmux -V")

    on_macos do
      assert_match "__info_plist", shell_output("otool -l #{bin}/tmux")
      assert_match "com.github.tmux", shell_output("codesign -dvvv #{bin}/tmux 2>&1")
      assert_match "patched build", shell_output("#{bin}/tmux-lnp-check #{bin}/tmux")
    end
  end
end
