#!/usr/bin/env python3
"""
Generates Formula/tmux.rb from homebrew-core, with our macOS patch applied.

Why: macOS 15+ blocks local network traffic for processes without a
recognisable app identity in the parent chain. tmux daemonises and is signed
ad-hoc without a bundle ID, so anything you run inside tmux (node, python, go)
gets EHOSTUNREACH on LAN addresses. The fix is to link an Info.plist into the
__TEXT,__info_plist section and sign ad-hoc afterwards.

This approach does not copy the formula; it re-derives it from core every time.
That way we follow upstream automatically: new versions, changed dependencies,
adjusted configure flags.

If the injection fails because core changed structurally, this script aborts
with an error instead of silently writing something wrong.
"""

from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

CORE_URL = "https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/t/tmux.rb"
OUT = Path(__file__).resolve().parent.parent / "Formula" / "tmux.rb"

HEADER = """# NOTE: this file is generated by scripts/generate-tmux-formula.py
# Do not edit by hand; change the script and run it again.
#
# Derived from homebrew-core with a single addition: an Info.plist is linked
# into the binary so macOS recognises tmux for Local Network Privacy. Without
# that patch, anything you run inside tmux gets EHOSTUNREACH on LAN addresses.
#
# Background: https://colosieve.com/posts/fixing-tmux-local-network-privacy-macos/

"""

PLIST_BLOCK = '''
    if OS.mac?
      (buildpath/"Info.plist").write <<~XML
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleIdentifier</key>
            <string>com.github.tmux</string>
            <key>CFBundleName</key>
            <string>tmux</string>
            <key>CFBundleVersion</key>
            <string>#{version}</string>
            <key>NSLocalNetworkUsageDescription</key>
            <string>tmux runs terminal sessions that may access hosts on the local network.</string>
        </dict>
        </plist>
      XML

      ENV.append "LDFLAGS", "-Wl,-sectcreate,__TEXT,__info_plist,#{buildpath}/Info.plist"
    end
'''

CODESIGN_BLOCK = '''
    if OS.mac?
      # Sign ad-hoc after the plist has been linked in; without a valid
      # signature macOS ignores the section.
      system "codesign", "--sign", "-", "--force", bin/"tmux"

      # `tmux -V` cannot carry a marker: plugin managers parse that string and
      # compare it numerically, so a suffix would break them. This helper gives
      # the same answer in one command instead.
      (bin/"tmux-lnp-check").write <<~SH
        #!/bin/sh
        # Report whether a tmux is the patched build from this tap.
        # Checks the tmux in PATH, or the binary given as first argument.

        bin=${1:-$(command -v tmux)}
        [ -n "$bin" ] && [ -x "$bin" ] || { echo "tmux: not found"; exit 1; }

        plist=no
        otool -l "$bin" 2>/dev/null | grep -q __info_plist && plist=yes
        ident=$(codesign -dvvv "$bin" 2>&1 | sed -n 's/^Identifier=//p')

        echo "binary:     $bin"
        echo "version:    $("$bin" -V 2>/dev/null)"
        echo "Info.plist: $plist"
        echo "identifier: ${ident:-none}"

        if [ "$plist" = yes ] && [ "$ident" = com.github.tmux ]; then
          echo "result:     patched build, Local Network Privacy can work"
          exit 0
        fi

        echo "result:     UNPATCHED, no Info.plist (probably homebrew-core's tmux)"
        echo "fix:        brew install --build-from-source frankhommers/tap/tmux"
        exit 1
      SH
      chmod 0755, bin/"tmux-lnp-check"
    end
'''

CAVEATS_AND_TEST = '''
  def caveats
    return unless OS.mac?

    <<~EOS
      This tmux embeds an Info.plist so macOS recognises it for Local Network
      Privacy.

      A running tmux server keeps the old binary in memory. Start a separate
      server to test without losing your sessions:

        tmux -L test new-session

      If no prompt appears, go to System Settings -> Privacy & Security ->
      Local Network and enable 'tmux'.

      To check which tmux you are running (this build or homebrew-core's
      unpatched one):

        tmux-lnp-check
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tmux -V")

    on_macos do
      assert_match "__info_plist", shell_output("otool -l #{bin}/tmux")
      assert_match "com.github.tmux", shell_output("codesign -dvvv #{bin}/tmux 2>&1")
      assert_match "patched build", shell_output("#{bin}/tmux-lnp-check #{bin}/tmux")
    end
  end
end
'''


def die(msg: str) -> None:
    print(f"ERROR: {msg}", file=sys.stderr)
    print(
        "\nThe structure of homebrew-core's tmux.rb has probably changed.\n"
        "Update scripts/generate-tmux-formula.py.",
        file=sys.stderr,
    )
    sys.exit(1)


def fetch_core() -> str:
    req = urllib.request.Request(CORE_URL, headers={"User-Agent": "homebrew-tap-sync"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        if resp.status != 200:
            die(f"could not fetch core formula (HTTP {resp.status})")
        return resp.read().decode("utf-8")


def strip_bottle(src: str) -> str:
    """Core's bottles belong to core's unpatched build. Keeping them would mean
    Homebrew downloads that binary and skips our patch entirely."""
    pattern = re.compile(r"\n  bottle do\n.*?\n  end\n", re.DOTALL)
    if not pattern.search(src):
        die("no bottle block found to remove")
    return pattern.sub("\n", src, count=1)


def patch_desc(src: str) -> str:
    pattern = re.compile(r'^  desc "([^"]*)"$', re.MULTILINE)
    if not pattern.search(src):
        die("desc line not found")
    return pattern.sub(
        r'  desc "\1 (with Info.plist for macOS Local Network Privacy)"', src, count=1
    )


def inject_plist(src: str) -> str:
    """Insert right after 'def install', before the rest of the installation."""
    marker = "\n  def install\n"
    if marker not in src:
        die("'def install' not found")
    return src.replace(marker, marker + PLIST_BLOCK, 1)


def inject_codesign(src: str) -> str:
    """At the end of def install, just before its closing 'end'.

    We locate the end of the install method by cutting at the first line that
    consists of 'end' at indentation level 2.
    """
    start = src.index("\n  def install\n")
    end_match = re.search(r"\n  end\n", src[start:])
    if not end_match:
        die("end of 'def install' not found")
    insert_at = start + end_match.start()
    return src[:insert_at] + "\n" + CODESIGN_BLOCK.rstrip("\n") + src[insert_at:]


def replace_tail(src: str) -> str:
    """Replace core's own caveats/test with ours."""
    # Drop everything from a 'def caveats' or 'test do' onwards.
    for marker in ("\n  def caveats\n", "\n  test do\n"):
        idx = src.find(marker)
        if idx != -1:
            return src[:idx] + CAVEATS_AND_TEST
    # Neither present: just replace the final 'end'.
    idx = src.rstrip().rfind("\nend")
    if idx == -1:
        die("could not determine the end of the class")
    return src[:idx] + CAVEATS_AND_TEST


def main() -> None:
    src = fetch_core()

    if "class Tmux < Formula" not in src:
        die("this does not look like a tmux formula")

    src = strip_bottle(src)
    src = patch_desc(src)
    src = inject_plist(src)
    src = inject_codesign(src)
    src = replace_tail(src)
    src = HEADER + src

    # Sanity check: is everything actually in there?
    for needle in ("__info_plist", "codesign", "NSLocalNetworkUsageDescription", "tmux-lnp-check"):
        if needle not in src:
            die(f"'{needle}' missing from the result")
    if "bottle do" in src:
        die("bottle block is still present")

    version = re.search(r'url ".*/tmux-([^/"]+)\.tar\.gz"', src)
    print(f"core version: {version.group(1) if version else 'unknown'}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    old = OUT.read_text() if OUT.exists() else ""
    if old == src:
        print("no change")
        return

    OUT.write_text(src)
    print(f"written: {OUT}")


if __name__ == "__main__":
    main()
